# Generated by Django 6.0 on 2025-12-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.EmailField(db_index=True, max_length=254)),
                ('admin_name', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('onboard', 'Onboard User'), ('activate', 'Activate User'), ('deactivate', 'Deactivate User'), ('update_role', 'Update Role'), ('update_name', 'Update Name'), ('update', 'Update User')], db_index=True, max_length=50)),
                ('target_user_email', models.EmailField(max_length=254)),
                ('target_user_name', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Admin Activity Log',
                'verbose_name_plural': 'Admin Activity Logs',
                'db_table': 'admin_activity_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
