"""
Universal Google OAuth Token Generator.

Generates OAuth tokens with the FULL scope superset needed by every agent
(gmail, calendar, docs, sheets, drive) and automatically updates every .env
file that any agent reads from:
  - supervisor-agent/.env   (the central credential store — source of truth)
  - gmail-agent/.env        (for running gmail-agent standalone)

No hardcoded values. No manual editing. One script, run once, everything works.

Usage:
    cd gmail-agent
    python generate_gmail_tokens.py
"""

import json
from pathlib import Path
from typing import Dict, List, Optional

from google_auth_oauthlib.flow import InstalledAppFlow


# Full scope superset — every sub-agent accepts whatever scopes are present
# on the token (no strict runtime check), so granting them all here means a
# single token works everywhere without any per-agent tuning.
SCOPES: List[str] = [
    # Gmail
    "https://www.googleapis.com/auth/gmail.send",
    "https://www.googleapis.com/auth/gmail.modify",
    "https://www.googleapis.com/auth/gmail.readonly",
    # Calendar
    "https://www.googleapis.com/auth/calendar",
    "https://www.googleapis.com/auth/calendar.events",
    # Docs
    "https://www.googleapis.com/auth/documents",
    # Sheets
    "https://www.googleapis.com/auth/spreadsheets",
    # Drive
    "https://www.googleapis.com/auth/drive",
]

# Keys this script owns end-to-end. The .env writer touches ONLY these lines;
# every other variable in the target files is preserved untouched.
_MANAGED_KEYS = (
    "GOOGLE_ACCESS_TOKEN",
    "GOOGLE_REFRESH_TOKEN",
    "GOOGLE_CLIENT_ID",
    "GOOGLE_CLIENT_SECRET",
)
_AUTO_MARKER = "# Google OAuth Tokens (auto-generated by generate_gmail_tokens.py)"


def _find_credentials_json() -> Optional[Path]:
    """Locate credentials.json. Prefer the centralized location, fall back to
    the per-agent copy for backwards compatibility."""
    script_dir = Path(__file__).resolve().parent  # gmail-agent/
    repo_root = script_dir.parent

    candidates = [
        repo_root / "supervisor-agent" / "credentials.json",  # preferred (central)
        script_dir / "credentials.json",                      # fallback (legacy)
    ]
    for path in candidates:
        if path.exists():
            print(f"  Using credentials.json from: {path}")
            return path
    return None


def _update_env(env_path: Path, updates: Dict[str, str]) -> None:
    """Atomically replace the four managed keys in an .env file.

    Strategy: read → drop any old copies of the managed keys (wherever they
    live) and the old auto-marker block → append a single fresh block at the
    bottom. Every unrelated line (other variables, comments, blank lines) is
    preserved verbatim.
    """
    env_path.parent.mkdir(parents=True, exist_ok=True)
    if not env_path.exists():
        env_path.touch()

    with env_path.open("r", encoding="utf-8") as f:
        original_lines = f.readlines()

    kept: List[str] = []
    skip_leading_blank = False
    for line in original_lines:
        stripped = line.strip()
        if stripped == _AUTO_MARKER:
            # Drop the old marker and the trailing blank line that usually
            # precedes it in our own writes.
            skip_leading_blank = True
            continue
        key = stripped.split("=", 1)[0].strip() if "=" in stripped else ""
        if key in _MANAGED_KEYS:
            continue
        if skip_leading_blank and stripped == "":
            skip_leading_blank = False
            continue
        skip_leading_blank = False
        kept.append(line)

    # Trim trailing blanks so the new block lands cleanly.
    while kept and kept[-1].strip() == "":
        kept.pop()

    new_block = ["\n", f"{_AUTO_MARKER}\n"]
    for key in _MANAGED_KEYS:
        value = updates.get(key)
        if value:
            new_block.append(f"{key}={value}\n")

    with env_path.open("w", encoding="utf-8") as f:
        f.writelines(kept + new_block)


def _prompt_login_hint() -> Optional[str]:
    """Ask for an optional login hint. Blank input ⇒ pick in the browser.
    Nothing is hardcoded."""
    print("\nWhich Google account do you want to authorize?")
    print("  [enter]    - let me choose in the browser (no hint)")
    print("  <email>    - pre-select this account in the browser")
    answer = input("Account email (or press Enter to skip): ").strip()
    return answer or None


def generate_tokens() -> bool:
    print("=" * 64)
    print("  Google OAuth Token Generator  -  universal for all sub-agents")
    print("=" * 64)
    print("Scopes requested:")
    for scope in SCOPES:
        print(f"  - {scope}")
    print("-" * 64)

    creds_path = _find_credentials_json()
    if creds_path is None:
        print(
            "\n[ERROR] credentials.json not found. Looked in:\n"
            "  supervisor-agent/credentials.json  (preferred)\n"
            "  gmail-agent/credentials.json       (fallback)\n"
            "Place your OAuth client's credentials.json in one of those paths\n"
            "and rerun this script."
        )
        return False

    login_hint = _prompt_login_hint()
    if login_hint:
        print(f"\n  Pre-selecting account: {login_hint}")
    else:
        print("\n  No account pre-selected; choose in the browser.")

    flow = InstalledAppFlow.from_client_secrets_file(str(creds_path), SCOPES)

    # access_type=offline + prompt=consent are REQUIRED to guarantee a
    # refresh_token is issued. Without these two, Google may silently omit
    # the refresh_token (e.g. on re-authorization of an already-granted app).
    server_kwargs: Dict = {
        "port": 0,
        "prompt": "select_account consent",
        "access_type": "offline",
        "include_granted_scopes": "true",
    }
    if login_hint:
        server_kwargs["login_hint"] = login_hint

    print("\n  Opening browser for consent...\n")
    creds = flow.run_local_server(**server_kwargs)

    if not (creds and creds.valid):
        print("[ERROR] Authorization did not complete. No tokens written.")
        return False

    if not creds.refresh_token:
        print(
            "\n[ERROR] Google did not issue a refresh_token.\n"
            "This normally means the app has already been authorized for this\n"
            "account. To fix:\n"
            "  1. Open https://myaccount.google.com/permissions\n"
            "  2. Remove this app's existing grant\n"
            "  3. Rerun this script"
        )
        return False

    # Pull client_id / client_secret straight out of credentials.json so the
    # runtime agents have everything they need — no manual .env editing.
    with creds_path.open("r", encoding="utf-8") as f:
        cred_data = json.load(f)
    client_block = cred_data.get("installed") or cred_data.get("web") or {}
    client_id = client_block.get("client_id", "")
    client_secret = client_block.get("client_secret", "")
    if not (client_id and client_secret):
        print(
            "[ERROR] credentials.json is missing client_id / client_secret under\n"
            "the 'installed' or 'web' block. The file is malformed."
        )
        return False

    updates = {
        "GOOGLE_ACCESS_TOKEN": creds.token,
        "GOOGLE_REFRESH_TOKEN": creds.refresh_token,
        "GOOGLE_CLIENT_ID": client_id,
        "GOOGLE_CLIENT_SECRET": client_secret,
    }

    # Write to every .env file any agent reads from. supervisor-agent/.env is
    # the source of truth (the supervisor forwards credentials to every sub-
    # agent via HTTP), but we also refresh gmail-agent/.env so the agent can
    # run standalone for dev/testing.
    script_dir = Path(__file__).resolve().parent   # gmail-agent/
    repo_root = script_dir.parent

    targets = [
        ("supervisor-agent", repo_root / "supervisor-agent" / ".env"),
        ("gmail-agent",      script_dir / ".env"),
    ]

    print("\n  Writing tokens to .env files:")
    for label, path in targets:
        _update_env(path, updates)
        print(f"    [OK] {label}/.env  ({path})")

    print(
        "\n" + "=" * 64
        + f"\n  SUCCESS - {len(SCOPES)} scopes granted, {len(updates)} keys written"
        + "\n  Next step: restart every running agent process so they pick up"
        + "\n  the new tokens."
        + "\n" + "=" * 64
    )
    return True


if __name__ == "__main__":
    ok = generate_tokens()
    raise SystemExit(0 if ok else 1)
